import { Event } from './types';

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'React Summit 2025',
    description: 'Join us for the biggest React conference of the year featuring talks from industry leaders, hands-on workshops, and networking opportunities. Learn about the latest in React 19, Server Components, and modern web development practices.',
    date: '2025-01-15',
    time: '09:00 AM',
    location: 'San Francisco, CA',
    category: 'Technology',
    capacity: 500,
    attending: 342,
    image: 'https://images.unsplash.com/photo-1582192523174-a3cc17d5b796?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    organizerId: '1',
    organizerName: 'Tech Events Inc',
    organizerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tech',
    attendees: [],
  },
  {
    id: '2',
    title: 'Startup Pitch Night',
    description: 'Witness innovative startups pitch their ideas to top venture capitalists. Network with founders, investors, and fellow entrepreneurs in this exciting evening event.',
    date: '2025-01-20',
    time: '06:00 PM',
    location: 'New York, NY',
    category: 'Business',
    capacity: 150,
    attending: 89,
    image: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    organizerId: '2',
    organizerName: 'Venture Hub',
    organizerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=venture',
    attendees: [],
  },
  {
    id: '3',
    title: 'Summer Music Festival',
    description: 'An unforgettable outdoor music experience featuring top artists across multiple genres. Three stages, food trucks, and amazing vibes all weekend long.',
    date: '2025-06-10',
    time: '12:00 PM',
    location: 'Austin, TX',
    category: 'Music',
    capacity: 5000,
    attending: 4823,
    image: 'https://images.unsplash.com/photo-1656283384093-1e227e621fad?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    organizerId: '3',
    organizerName: 'Live Nation Events',
    organizerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=music',
    attendees: [],
  },
  {
    id: '4',
    title: 'Professional Networking Mixer',
    description: 'Connect with professionals from various industries in a relaxed, social setting. Perfect for expanding your network and exploring new opportunities.',
    date: '2025-01-25',
    time: '07:00 PM',
    location: 'Chicago, IL',
    category: 'Networking',
    capacity: 100,
    attending: 67,
    image: 'https://images.unsplash.com/photo-1675716921224-e087a0cca69a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    organizerId: '4',
    organizerName: 'Network Pro',
    organizerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=network',
    attendees: [],
  },
  {
    id: '5',
    title: 'Championship Finals',
    description: 'Watch the thrilling championship finals live! Experience the energy of the crowd and witness history in the making. Limited seats available.',
    date: '2025-03-15',
    time: '07:30 PM',
    location: 'Los Angeles, CA',
    category: 'Sports',
    capacity: 20000,
    attending: 18456,
    image: 'https://images.unsplash.com/photo-1565483276060-e6730c0cc6a1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    organizerId: '5',
    organizerName: 'Sports League',
    organizerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sports',
    attendees: [],
  },
  {
    id: '6',
    title: 'Modern Art Exhibition',
    description: 'Explore contemporary art from emerging and established artists. Interactive installations, guided tours, and artist talks throughout the exhibition period.',
    date: '2025-02-01',
    time: '10:00 AM',
    location: 'Boston, MA',
    category: 'Art',
    capacity: 200,
    attending: 134,
    image: 'https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    organizerId: '6',
    organizerName: 'Art Gallery NYC',
    organizerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=art',
    attendees: [],
  },
  {
    id: '7',
    title: 'Full Stack Developer Workshop',
    description: 'Intensive 2-day workshop covering MERN stack development, deployment strategies, and best practices. Build a complete application from scratch.',
    date: '2025-01-18',
    time: '09:00 AM',
    location: 'Seattle, WA',
    category: 'Technology',
    capacity: 50,
    attending: 50,
    image: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    organizerId: '1',
    organizerName: 'Code Academy',
    organizerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=code',
    attendees: [],
  },
  {
    id: '8',
    title: 'Digital Marketing Summit',
    description: 'Learn the latest strategies in SEO, social media marketing, content creation, and analytics. Featuring case studies from Fortune 500 companies.',
    date: '2025-02-10',
    time: '08:30 AM',
    location: 'Miami, FL',
    category: 'Business',
    capacity: 300,
    attending: 245,
    image: 'https://images.unsplash.com/photo-1582192523174-a3cc17d5b796?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    organizerId: '2',
    organizerName: 'Marketing Pros',
    organizerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=marketing',
    attendees: [],
  },
];

export const categories = [
  'All Categories',
  'Technology',
  'Business',
  'Music',
  'Sports',
  'Art',
  'Networking',
];
